Bump to 3.0.3-1 and upgrade dependencies
butterproject/vlc-android-sdk pull request #15
Opened 2018-03-02 15:06 UTC by carlonzo

2018-03-02 15:11 UTC, carlonzo commented
@blazsolar is CircleCI configured with this project? how can I check the status?

2018-03-02 15:36 UTC, blazsolar commented
Hi, can you reopen this pull request. As I just enabled PR building on CircleCI. After that you should see CI status. 

Thanks

2018-03-03 09:34 UTC, blazsolar requested changes
Please update the comment and also bump version in `README.md` file. After that I will merge this PR. Thanks

2018-03-03 09:34 UTC, blazsolar commented on gradle.properties
> +VERSION_CODE=3003001
this should be `3000301`

2018-03-03 19:20 UTC, carlonzo commented on gradle.properties
> +VERSION_CODE=3003001
thanks! I was not sure about that :)

2018-03-03 19:25 UTC, carlonzo commented
@blazsolar done. thanks

2018-03-03 21:04 UTC, blazsolar approved these changes

2018-03-03 21:05 UTC, blazsolar commented
Thanks for contributing, i'll make release tomorrow

2018-03-04 11:24 UTC, merged